### ISSUE TITLE
Error in skull stripping step

### ISSUE THREAD

**Issue by reborn781025** [dorianps/LINDA#23] opened 2019-07-19 09:59 UTC
Dear Dorian,

I just newly started using LINDA v0.5.0 with ANTsRCore v0.7.0 and ANTsR v0.4.9. However, I encountered the following error:

Skull stripping... (long process)Error in if (is.na(mask)) { : argument is not interpretable as logical

Could you please help me with how to fix this error? Thank you.

Best,
Rita

**Comment by dorianps** [comment] 2019-07-19 13:49
This used to work, so the only thing I can think of is some recent change in ANTsR. Are both software the most recent (LINDA, ANTsR and ANTsRCore)?

**Comment by reborn781025** [comment] 2019-07-19 14:53
Hi,

I believe they are all the most recent versions. By the way, I was running it using RStudio version 1.1.463 but I saw the same error when I tried R version 3.5.2

Would you suggest that I post this issue on ANTsR site? Or would you look into this issue?

Many thanks,
Rita

**Comment by dorianps** [comment] 2019-07-19 17:08
I need to look into this. If you can send me your mprage that would be
helpful, just in case the data is the problem, otherwise I will use another
test mprage.

**Comment by reborn781025** [comment] 2019-07-20 01:37
Thanks a lot for looking into this. Could you provide me your email?
I tested two datasets and encountered the same error. I will send you two mprage from two datasets.

**Comment by dorianps** [comment] 2019-07-20 03:13
Use this address please (remove #)
al#bnet at gmai#l.com

**Comment by dorianps** [comment] 2019-07-20 15:03
Ok, I ran LINDA on linux, older installation and works fine. Here is the native segmentation for TP2.

[Prediction3_native.nii.gz](https://github.com/dorianps/LINDA/files/3413722/Prediction3_native.nii.gz)

The error you show above came up yesterday during Travis tests for LESYMAP as well, but [only for OSX](https://travis-ci.org/dorianps/LESYMAP/jobs/561306986). I don't know yet what is wrong with the OSX installation of ANTsR. Can you confirm if you also encountered the problem on an Apple computer?

I may open an ANTsR issue later to ask @stnava and other developers where is this coming from. In my code, the error comes when I check `is.na(mask)` where mask can be an antsImage or default NA. The LINDA code has not changed, so it's either changes in ANTsR or something weird happening on OSX.

**Comment by reborn781025** [comment] 2019-07-20 15:12
Yes, I ran ANTsR and LINDA in R using an iMac and saw the error comes from is.na(mask). Are you implying it may work if I use Windows system? I could probably give it a try and let you know if it works. Thanks.

**Comment by dorianps** [comment] 2019-07-20 15:19
Thanks for confirming.

It should work on Linux, whether native or Windows subsystem. There is no native ANTsR for Windows.

**Comment by reborn781025** [comment] 2019-07-20 16:28
Thank you for your information. Please let me know if you get the solution. Thanks again.

**Comment by dorianps** [comment] 2019-07-20 21:59
Rita, turns out the problem is a change in ANTsR, it has nothing to do with Apple computers. I will need to change some code to resolve the issue, will let you know when is done.

Meanwhile, if you are in a hurry you could get away with installing ANTsRCore and ANTsR from at least 1 month older.

**Comment by reborn781025** [comment] 2019-07-21 15:48
Dorian, I sincerely appreciate all your prompt responses and investigation.

**Comment by dorianps** [comment] 2019-07-22 01:45
You are welcome. The problem arises from ANTsR and needs to be fixed there.  The temporary solution for you is to use an ANTsRCore commit from last month. I tested this solution and worked with your TP2 example. From a shell prompt:

```
git clone https://github.com/ANTsX/ANTsRCore.git
cd ANTsRCore
git checkout 25f0f8a469950f3c66ece4c2632bb15d30cea8de
R CMD INSTALL .
```

We are discussing this problem in an open ANTsR issue, you can check there for a more permanent solution https://github.com/ANTsX/ANTsR/issues/274

**Comment by dorianps** [comment] 2019-09-07 18:25
This error was fixed in ANTsR back in July, closing issue.

**Closed by dorianps** 2019-09-07 18:25 UTC
